---
- name: Check Python version
  command: python3 --version
  register: python_version
  ignore_errors: true

- name: Display Python version
  debug:
    msg: "Found Python version: {{ python_version.stdout }}"

- name: Read requirements.txt
  slurp:
    src: "{{ repo_path }}/requirements.txt"
  register: requirements_file

- name: Set requirements list
  set_fact:
    requirements_list: "{{ requirements_file['content'] | b64decode | split('\n') | select('match', '^[^#\\s].*') | list }}"

- name: Print Python requirements
  debug:
    msg: |
      Python requirements for {{ repo_name }}:
      {% for req in requirements_list %}
        - {{ req }}
      {% endfor %}
  when: requirements_list | length > 0 