---
- name: Check Python version
  command: python3 --version
  register: python_version
  ignore_errors: true

- name: Display Python version
  debug:
    msg: "Found Python version: {{ python_version.stdout }}"


- name: Show requirements.txt contents
  command: cat "{{ repos_dir }}/{{ repo_name }}/requirements.txt"
  register: req_contents
  changed_when: false
  ignore_errors: true

- name: Print requirements.txt
  debug:
    msg: "{{ req_contents.stdout }}"
  when: req_contents.stdout is defined 