---
- name: Process repositories
  hosts: localhost
  gather_facts: true
  vars:
    repos_dir: "{{ lookup('env', 'PWD') }}/repos"

  tasks:
    - name: Get list of repositories
      find:
        paths: "{{ repos_dir }}"
        patterns: "*"
        file_type: directory
      register: repo_dirs

    - name: Count total repositories
      set_fact:
        total_repos: "{{ repo_dirs.files | length }}"

    - name: Display total repositories
      debug:
        msg: "Total repositories found: {{ total_repos }}"

    - name: Process each repository
      include_tasks: process_repo.yml
      loop: "{{ repo_dirs.files }}"
      loop_control:
        loop_var: repo
      vars:
        repo_name: "{{ repo.path | basename }}"
        repo_path: "{{ repo.path }}"
      ignore_errors: true 